# Shared constants for win rates and related handlers

REGION_LIST = [
    "Americas",
    "Asia",
    "Europe"
]

TIER_LIST = [
    "Bronze",
    "Silver",
    "Gold",
    "Platinum",
    "Diamond",
    "Master",
    "Grandmaster",
    "All"
]

MAP_LIST = [
    "all-maps",
    "antarctic-peninsula",
    "busan",
    "ilios",
    "lijang-tower",
    "nepal",
    "oasis",
    "samoa",
    "circuit-royal",
    "dorado",
    "havana",
    "junkertown",
    "rialto",
    "route-66",
    "shambali-monastery",
    "watchpoint-gibraltar",
    "aatlis",
    "new-junk-city",
    "suravasa",
    "blizzard-world",
    "eichenwalde",
    "hollywood",
    "kings-row",
    "midtown",
    "numbani",
    "paraiso",
    "colosseo",
    "esperanca",
    "new-queen-street",
    "runasapi"
]

# HERO_LIST should be populated from your data source or maintained here if static
HERO_LIST = [
    "Ana",
    "Ashe",
    "Baptiste",
    "Bastion",
    "Brigitte",
    "Cassidy",
    "D.Va",
    "Doomfist",
    "Echo",
    "Freja",
    "Genji",
    "Hanzo",
    "Hazard",
    "Illari",
    "Junker Queen",
    "Junkrat",
    "Juno",
    "Kiriko",
    "Lifeweaver",
    "Lúcio",
    "Mauga",
    "Mei",
    "Mercy",
    "Moira",
    "Orisa",
    "Pharah",
    "Ramattra",
    "Reaper",
    "Reinhardt",
    "Roadhog",
    "Sigma",
    "Sojourn",
    "Soldier: 76",
    "Sombra",
    "Symmetra",
    "Torbjörn",
    "Tracer",
    "Venture",
    "Widowmaker",
    "Winston",
    "Wrecking Ball",
    "Wuyang",
    "Zarya",
    "Zenyatta"
]
