name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest for tests
        run: pip install pytest

      - name: Run unit tests
        run: |
          PYTHONPATH=src pytest tests

      - name: Prepare source layout for Lambda
        run: |
          cp -r src/handlers ./
          cp -r src/utils ./
          cp src/__init__.py ./

      - name: Install Serverless Framework v2
        run: npm install -g serverless@2

      - name: Install Serverless Plugins
        run: |
          npm install --save-dev serverless-python-requirements
          npm install --save-dev serverless-plugin-log-retention

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless
        env:
          OWL_SITE_DATA_BUCKET: ${{ secrets.OWL_SITE_DATA_BUCKET }}
        run: |
          serverless deploy --stage dev